import os

include: "rules/common.smk"
configfile: "config/config.yaml"


results_dir = config["results_dir"]
os.system(f"mkdir -p {results_dir}")

rule all:
    input:
        results_dir + "/done"

include: "rules/mmseqs.smk"
include: "rules/hhblits.smk"
