import os

include: "rules/common.smk"
configfile: "config/config.yaml"


rule all:
    input:
        "results/protein_clustering_results.tsv"

include: "rules/mmseqs.smk"
include: "rules/hhblits.smk"
include: "rules/mcl.smk"
